name: Bedingungen

on:
  push:
  workflow_dispatch:
   

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Auslöser anzeigen
        run: echo "Auslöser= ${{ github.event_name }}"

      - name: Nur bei Push
        if: github.event_name == 'push'
        run: echo "Branch ist ${{ github.ref_name }}"

      - name: Nur bei manueller Auslösung
        if: github.event_name == 'workflow_dispatch'
        run: echo "Du hast den Knopf gedrückt"


  