name: Zwei Jobs (Übung 6.2)

on:
  push:
  workflow_dispatch:
   
jobs:
  vorbereiten:
    runs-on: ubuntu-latest
    steps:
      - name: Begrüßung
        run: echo "Hallo, Vorbereitung läuft"


  arbeiten:
    runs-on: ubuntu-latest
    needs: vorbereiten
    steps:
      - name: 2. Meldung
        run: echo "Jetzt wird gearbeitet"